#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Oct 16 17:53:26 2017

@author: sitibanc
"""
from sklearn import linear_model
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import train_test_split
import pandas as pd

# Read Data
data = pd.read_csv('nyc-rolling-sales-processed.csv')
data = data.drop(data.columns[[0]], axis = 1)

# Split Features & Targets
targets = data['SALE PRICE']
features = data.drop('SALE PRICE', axis = 1)

# Split Training & Testing Data
trainX, testX, trainY, testY = train_test_split(targets, features, test_size = 0.25)

reg = linear_model.LinearRegression()